import React, { useState } from 'react';
import { X, Copy, Download, Printer, Check, FileJson, FileText } from 'lucide-react';
import { copyToClipboard, downloadJsonFile, downloadTextFile } from '../../lib/utils';
import { ProductAnalysis } from '../../types';

interface ExportModalProps {
  analysis: ProductAnalysis;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  analysis,
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopyMarkdown = async () => {
    const markdown = `# Prime Market — AI Product Intelligence Report
**Product:** ${analysis.productName}
**Category:** ${analysis.category}
**Original Price:** ${analysis.currency}${analysis.originalPrice.toLocaleString('en-IN')}
**Opportunity Score:** ${analysis.opportunityScore.overall}/100 (${analysis.opportunityScore.level})
**Market Demand:** ${analysis.marketDemand} | **Competition:** ${analysis.competitionLevel}
**Recommended Price Range:** ${analysis.currency}${analysis.recommendedPriceRange.min.toLocaleString('en-IN')} – ${analysis.currency}${analysis.recommendedPriceRange.max.toLocaleString('en-IN')} (Optimal: ${analysis.currency}${analysis.recommendedPriceRange.optimal.toLocaleString('en-IN')})

## Product Summary
${analysis.productSummary}

## Key Strengths
${analysis.strengths.map((s) => `- ${s}`).join('\n')}

## Critical Weaknesses & Risks
${analysis.weaknesses.map((w) => `- ${w}`).join('\n')}

## Actionable AI Recommendations
${analysis.recommendations.map((r, i) => `${i + 1}. **${r.title}** [${r.impact} Impact | ${r.category}]: ${r.description}`).join('\n')}

## Target Audience Segments
${analysis.targetAudience.map((t) => `### ${t.segment}\n* Demographics: ${t.demographics}\n* Motivation: ${t.buyingMotivation}`).join('\n\n')}

*Generated by Prime Market AI SaaS Engine on ${new Date(analysis.analyzedAt).toLocaleDateString()}*
`;

    const success = await copyToClipboard(markdown);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadJson = () => {
    const filename = `${analysis.productName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-analysis`;
    downloadJsonFile(filename, analysis);
  };

  const handleDownloadMarkdown = () => {
    const filename = `${analysis.productName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-report.md`;
    const markdown = `# Prime Market Intelligence Report: ${analysis.productName}\n\nGenerated: ${analysis.analyzedAt}\nOpportunity Score: ${analysis.opportunityScore.overall}/100\n\nSummary:\n${analysis.productSummary}`;
    downloadTextFile(filename, markdown);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xs no-print">
      <div className="relative w-full max-w-lg bg-[#18181b] rounded-xl shadow-2xl border border-[#27272a] p-6 animate-in fade-in zoom-in-95 duration-200">
        <div className="flex items-center justify-between pb-4 border-b border-[#27272a]">
          <div>
            <h3 className="text-lg font-bold text-[#fafafa]">
              Export Analysis Report
            </h3>
            <p className="text-xs text-[#71717a] mt-0.5">
              {analysis.productName}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1 rounded-lg text-[#71717a] hover:text-[#fafafa] hover:bg-[#27272a] cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 py-5">
          {/* Copy Markdown */}
          <button
            type="button"
            id="export-copy-btn"
            onClick={handleCopyMarkdown}
            className="flex flex-col items-start gap-1.5 p-4 rounded-xl border border-[#27272a] hover:border-indigo-500 hover:bg-[#27272a]/50 text-left transition-all group cursor-pointer"
          >
            <div className="w-8 h-8 rounded-lg bg-[#27272a] text-indigo-400 flex items-center justify-center group-hover:scale-110 transition-transform">
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            </div>
            <span className="font-semibold text-sm text-[#fafafa] mt-1">
              {copied ? 'Copied to Clipboard!' : 'Copy Summary'}
            </span>
            <span className="text-xs text-[#71717a]">
              Formatted markdown ready to paste into Slack or Notion
            </span>
          </button>

          {/* Download JSON */}
          <button
            type="button"
            id="export-json-btn"
            onClick={handleDownloadJson}
            className="flex flex-col items-start gap-1.5 p-4 rounded-xl border border-[#27272a] hover:border-emerald-500 hover:bg-[#27272a]/50 text-left transition-all group cursor-pointer"
          >
            <div className="w-8 h-8 rounded-lg bg-[#27272a] text-emerald-400 flex items-center justify-center group-hover:scale-110 transition-transform">
              <FileJson className="w-4 h-4" />
            </div>
            <span className="font-semibold text-sm text-[#fafafa] mt-1">
              Download JSON
            </span>
            <span className="text-xs text-[#71717a]">
              Structured raw data for developer APIs & backups
            </span>
          </button>

          {/* Download Markdown */}
          <button
            type="button"
            id="export-markdown-btn"
            onClick={handleDownloadMarkdown}
            className="flex flex-col items-start gap-1.5 p-4 rounded-xl border border-[#27272a] hover:border-blue-500 hover:bg-[#27272a]/50 text-left transition-all group cursor-pointer"
          >
            <div className="w-8 h-8 rounded-lg bg-[#27272a] text-blue-400 flex items-center justify-center group-hover:scale-110 transition-transform">
              <FileText className="w-4 h-4" />
            </div>
            <span className="font-semibold text-sm text-[#fafafa] mt-1">
              Download .MD File
            </span>
            <span className="text-xs text-[#71717a]">
              Complete offline documentation file
            </span>
          </button>

          {/* Print Report */}
          <button
            type="button"
            id="export-print-btn"
            onClick={handlePrint}
            className="flex flex-col items-start gap-1.5 p-4 rounded-xl border border-[#27272a] hover:border-purple-500 hover:bg-[#27272a]/50 text-left transition-all group cursor-pointer"
          >
            <div className="w-8 h-8 rounded-lg bg-[#27272a] text-purple-400 flex items-center justify-center group-hover:scale-110 transition-transform">
              <Printer className="w-4 h-4" />
            </div>
            <span className="font-semibold text-sm text-[#fafafa] mt-1">
              Print / Save as PDF
            </span>
            <span className="text-xs text-[#71717a]">
              Clean paper or PDF formatted document
            </span>
          </button>
        </div>

        <div className="pt-3 border-t border-[#27272a] flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-[#fafafa] bg-[#27272a] hover:bg-[#3f3f46] rounded-lg transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
